#!/bin/bash
# @author stev leibelt <artodeto@bazzline.net>
# @since 2015-08-20

PATH_TO_LOCK='/usr/local/bin/lock'

if [ -f $PATH_TO_LOCK ]; then
    if [ -h $PATH_TO_LOCK ]; then
        sudo rm $PATH_TO_LOCK
    else
        echo $PATH_TO_LOCK' is not the expected softlink'
        exit 1
    fi
else
    echo 'lock is not installed'
    exit 1
fi
